ALTER TABLE "Call" ADD COLUMN "userId" TEXT;

CREATE INDEX "Call_userId_idx" ON "Call"("userId");

ALTER TABLE "Call" ADD CONSTRAINT "Call_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
